apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: kirigaikabuto/go-k8s-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: go-app-config
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: go-app
